{% set version = "0.5.2" %}

package:
  name: r-crul
  version: {{ version }}

source:
  fn: crul_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/crul_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/crul/crul_{{ version }}.tar.gz
  sha256: e01b25606dd113941537a9399d90370fa8de133ae7b2d8c82aa8979525dad269

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-r6 >=2.2.0
    - r-curl >=3.1
    - r-httpcode >=0.2.0
    - r-mime
    - r-urltools >=1.6.0
  run:
    - r-base
    - r-r6 >=2.2.0
    - r-curl >=3.1
    - r-httpcode >=0.2.0
    - r-mime
    - r-urltools >=1.6.0

test:
  commands:
    - $R -e "library('crul')"  # [not win]
    - "\"%R%\" -e \"library('crul')\""  # [win]

about:
  home: https://cran.r-project.org/package=crul
  license: MIT
  license_file: LICENSE
  summary: A simple HTTP client, with tools for making HTTP requests, and mocking HTTP requests.
    The package is built on R6, and takes inspiration from Ruby's 'faraday' gem (<https

extra:
  recipe-maintainers:
    - ocefpaf
