{% set version = "1.4.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-crul
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/crul_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/crul/crul_{{ version }}.tar.gz
  sha256: 405c77f191f30ffdbf8c05542ff5dff61059e9c731d2dc5ff0bfccb616314147

build:
  number: 1
  noarch: generic
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6 >=2.2.0
    - r-curl >=3.3
    - r-httpcode >=0.2.0
    - r-jsonlite
    - r-mime
    - r-urltools >=1.6.0
  run:
    - r-base
    - r-r6 >=2.2.0
    - r-curl >=3.3
    - r-httpcode >=0.2.0
    - r-jsonlite
    - r-mime
    - r-urltools >=1.6.0

test:
  commands:
    - $R -e "library('crul')"           # [not win]
    - "\"%R%\" -e \"library('crul')\""  # [win]

about:
  home: https://github.com/ropensci/crul (devel) https://ropenscilabs.github.io/http-testing-book/ (user manual)
  license: MIT
  summary: A simple HTTP client, with tools for making HTTP requests, and mocking HTTP requests. The package is built on R6, and takes inspiration from Ruby's 'faraday' gem (<https://rubygems.org/gems/faraday>). The package name is a play on curl, the widely used command line tool for HTTP, and this package is built on top
    of the R package 'curl', an interface to 'libcurl' (<https://curl.haxx.se/libcurl>).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: crul
# Title: HTTP Client
# Description: A simple HTTP client, with tools for making HTTP requests, and mocking HTTP requests. The package is built on R6, and takes inspiration from Ruby's 'faraday' gem (<https://rubygems.org/gems/faraday>). The package name is a play on curl, the widely used command line tool for HTTP, and this package is built on top of the R package 'curl', an interface to 'libcurl' (<https://curl.haxx.se/libcurl>).
# Version: 0.8.4
# License: MIT + file LICENSE
# Authors@R: c( person("Scott", "Chamberlain", role = c("aut", "cre"), email = "myrmecocystus@gmail.com", comment = c(ORCID = "0000-0003-1444-9135")) )
# URL: https://github.com/ropensci/crul (devel) https://ropenscilabs.github.io/http-testing-book/ (user manual)
# BugReports: https://github.com/ropensci/crul/issues
# Encoding: UTF-8
# Language: en-US
# Imports: curl (>= 3.3), R6 (>= 2.2.0), urltools (>= 1.6.0), httpcode (>= 0.2.0), jsonlite, mime
# Suggests: testthat, fauxpas (>= 0.1.0), webmockr (>= 0.1.0), knitr
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# X-schema.org-applicationCategory: Web
# X-schema.org-keywords: http, https, API, web-services, curl, download, libcurl, async, mocking, caching
# X-schema.org-isPartOf: https://ropensci.org
# NeedsCompilation: no
# Packaged: 2019-08-02 19:58:21 UTC; sckott
# Author: Scott Chamberlain [aut, cre] (<https://orcid.org/0000-0003-1444-9135>)
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-08-02 20:30:02 UTC
