travis:
  secure:
    BINSTAR_TOKEN: aLyItrovwt1XxMSKm4fMS/p8v/K3mwVP3EPex+w7O3O9KozqAt8wH3auLIOnfVkPuL14wRcyAfu1lfSCzb6O0fCQ5erSwKCYgUzc5AkBFMv3tZMkarPnpV4IIecFwlGAGLml1pP7bJ1UA5190iHGKeKgpv2nffwi+UI4apVI9OP6F88nsdbQ2+UrF2EGfUQQze48QVZR1hxes17W1SnnAjnIWFcvxueXLldjCl266pkNY+wpzRfJojsnd9Sp+yRtbB4l/dS3SdbiWNiqabr1KtOJikHsI/QC6WkTRJktzo8R6p10jni6RERpLLbWks0jrw3cGMjTJHBqqrjMc1tH6R1bBsiOSjNBvAHGCSf46TTAqI8E2NoWxP9AF689ssYQEj0Zrhkr3L7sGgKNvqE6fb9l2pu7P5ig1aDKfJm63OtqVas0gR42dkXejqA+fhtVSe9x0LGF4dUbBOxvFg1HeWpLy6VGdg2Hve9HjItyo7M+uJqEGOYWe9YmFNB9MRPQrWy4wQ5e6IUzh6NHu5+XlcN671lY/ldct+90R/wDNQYrP1wKNPJVHfEpMdjX1HVA6nQ4waJW4rCcuJOp8QnWyAx+f0fR5g2VGv0HnVEqyrKSD5+2+kdRSxY0Tzur6VSL2L9JsQ0EDryO90u2UNZNdmM+bsko2hm5o4VwOZewm7s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
